spring:
  .h2.console:
    enabled: true
    path: '/console'

  .datasource:
    url: 'jdbc:h2:C:/Users/Public/notesDB'
    username: 'sa'

  .jpa:
    database-platform: org.hibernate.dialect.H2Dialect